export const COUNTRY_NAME_TO_ISO: Record<string, string> = {
  nigeria: "NG",
  kenya: "KE",
  ghana: "GH",
  tanzania: "TZ",
  uganda: "UG",
  "south africa": "ZA",
  ethiopia: "ET",
  egypt: "EG",
  morocco: "MA",
  algeria: "DZ",
  sudan: "SD",
  cameroon: "CM",
  "ivory coast": "CI",
  senegal: "SN",
  botswana: "BW",
  zimbabwe: "ZW",
  zambia: "ZM",
  malawi: "MW",
  mozambique: "MZ",
  angola: "AO",
  rwanda: "RW",
  burundi: "BI",
  liberia: "LR",
  "sierra leone": "SL",
  guinea: "GN",
  gambia: "GM",
  togo: "TG",
  benin: "BJ",
  lesotho: "LS",
  namibia: "NA",
  swaziland: "SZ",
  eswatini: "SZ",
  mauritius: "MU",
  madagascar: "MG",
  "burkina faso": "BF",
  niger: "NE",
  mali: "ML",
  chad: "TD",
  congo: "CG",
  "democratic republic of congo": "CD",
  drc: "CD",
  "united states": "US",
  usa: "US",
  uk: "GB",
  "united kingdom": "GB",
};
